# Decap CMS config med GitHub backend (alternativ 1)

backend:
  name: github
  repo: helenaskagerlid/helenaswane # ditt GitHub-repo
  branch: main # branch som ska användas
  # auth_type: pkce                   # valfritt, kan tas bort
  commit_messages:
    create: "Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}>"
    update: "Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}>"
    delete: "Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}>"
    uploadMedia: "Upload “{{path}}” - {{author-name}} <{{author-login}}>"
    deleteMedia: "Delete “{{path}}” - {{author-name}} <{{author-login}}>"

media_folder: "public
public_folder: "/"

collections:
  - name: "blogPosts"
    label: "Blog"
    folder: "src/content/blog-posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - label: "Body"
        name: "body"
        widget: "markdown"
        editor_components: ["youtube"]

# Valfritt: logotyp och site URL
logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://helenaswane.netlify.app
