backend:
  name: git-gateway
  repo: helenaskagerlid/helenaswane
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/0af17602-575b-4bf6-9235-2fa4e9432076/pkce
  auth_token_endpoint: /sites/0af17602-575b-4bf6-9235-2fa4e9432076/token
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}>
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}>
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}>
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}>
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}>
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}>

auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://helenaswane.netlify.app

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: blogPosts
    label: Blog
    folder: src/content/blog-posts
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Featured Image, name: image, widget: image }
      - { label: Body, name: body, widget: markdown }
